POST http://localhost:8000/run
Content-Type: application/json

{
  "language": "cpp",
  "source_code": "#include <iostream>\n#include <string>\n#include <algorithm>\n\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    reverse(s.begin(), s.end());\n    cout << s << '\\n';\n}",
  "stdin": "ninte thantha aara myre",
  "memory_limit_kb" : 1022222
}

POST http://localhost:8000/run
Content-Type: application/json

{
  "language": "cpp",
  "source_code": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    const size_t SIZE = 1024ULL * 1024 * 1024;\n    vector<char> memory(SIZE);\n\n    for (size_t i = 0; i < SIZE; i += 4096) {\n        memory[i] = 1;\n    }\n\n    cout << \"Allocated 1 GB\\n\";\n    return 0;\n}",
  "stdin": ""
}