POST http://localhost:8000/run
Content-Type: application/json

{
  "language": "cpp",
  "source_code": "#include <iostream>\n\nint main() {\n    int i = 1;\n    while (i <= 5) {\n        std::cout << \"Hello World \" << i << std::endl;\n        i++;\n    }\n    return 0;\n}"
}